name: manual workflow
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  test:
    name: test-job-name
    runs-on: ubuntu-latest    

    steps:
    - name: run cli
      run: |
        pwd
        ls -l
